services:
  drone-vc-p:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      TG_BOT_TOKEN: $TG_BOT_TOKEN 
      DB_URI: $DB_URI
      OWNER_ID: $OWNER_ID
    resources:
      cpu: 1000m
      memory: 3Gi
